config/routes.rb
Rails.application.routes.draw do
  resources :t_user_accounts
  resources :t_people
  resources :t_facility_access_event_histories
  resources :events

  resources :events do
    collection do
         get 'sold'
    end
  end
  resources :t_orders do
  end
  resources :t_order_items do
  end
  resources :t_facility_access_event_histories do
  end
  resources :t_persons do
  end

end

app/models/t_facility_access_event_history.rb
class TFacilityAccessEventHistory < ActiveRecord::Base

       self.table_name="T_FACILITY_ACCESS_EVENT_HISTORY"
end

app/controllers/t_facility_access_event_histories_controller.rb
class TFacilityAccessEventHistoriesController < ApplicationController
  before_action :set_t_facility_access_event_history, only: [:show, :edit, :update, :destroy]

  # GET /t_facility_access_event_histories
  # GET /t_facility_access_event_histories.json
  def index
    @t_facility_access_event_histories = TFacilityAccessEventHistory.all
        @t_facility_access_event_histories_first = TFacilityAccessEventHistory.limit(5)
  end

  # GET /t_facility_access_event_histories/1
  # GET /t_facility_access_event_histories/1.json
  def show
  end

  # GET /t_facility_access_event_histories/new
  def new
    @t_facility_access_event_history = TFacilityAccessEventHistory.new
  end

  # GET /t_facility_access_event_histories/1/edit
  def edit
  end

  # POST /t_facility_access_event_histories
  # POST /t_facility_access_event_histories.json
  def create
    @t_facility_access_event_history = TFacilityAccessEventHistory.new(t_facility_access_event_history_params)

    respond_to do |format|
      if @t_facility_access_event_history.save
        format.html { redirect_to @t_facility_access_event_history, notice: 'T facility access event history was successfully created.' }
        format.json { render :show, status: :created, location: @t_facility_access_event_history }
      else
        format.html { render :new }
        format.json { render json: @t_facility_access_event_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /t_facility_access_event_histories/1
  # PATCH/PUT /t_facility_access_event_histories/1.json
  def update
    respond_to do |format|
      if @t_facility_access_event_history.update(t_facility_access_event_history_params)
        format.html { redirect_to @t_facility_access_event_history, notice: 'T facility access event history was successfully updated.' }
        format.json { render :show, status: :ok, location: @t_facility_access_event_history }
      else
        format.html { render :edit }
        format.json { render json: @t_facility_access_event_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /t_facility_access_event_histories/1
  # DELETE /t_facility_access_event_histories/1.json
  def destroy
    @t_facility_access_event_history.destroy
    respond_to do |format|
      format.html { redirect_to t_facility_access_event_histories_url, notice: 'T facility access event history was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_t_facility_access_event_history
      @t_facility_access_event_history = TFacilityAccessEventHistory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def t_facility_access_event_history_params
      params.require(:t_facility_access_event_history).permit(:first_name, :last_name, :person_id)
    end
end

app/helpers/t_facility_access_event_histories_helper.rb
module TFacilityAccessEventHistoriesHelper
end

app/views/t_facility_access_event_histories/_form.html.erb
<%= form_for(@t_facility_access_event_history) do |f| %>
  <% if @t_facility_access_event_history.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@t_facility_access_event_history.errors.count, "error") %> prohibited this t_facility_access_event_history from being saved:</h2>

      <ul>
      <% @t_facility_access_event_history.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :person_id %><br>
    <%= f.number_field :person_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/t_facility_access_event_histories/edit.html.erb
<h1>Editing T Facility Access Event History</h1>

<%= render 'form' %>

<%= link_to 'Show', @t_facility_access_event_history %> |
<%= link_to 'Back', t_facility_access_event_histories_path %>

app/views/t_facility_access_event_histories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing T Facility Access Event Histories</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Person</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <tr>
    <%=  @t_facility_access_event_histories.count %>
   </tr>
    <% @t_facility_access_event_histories_first.each do |t_facility_access_event_history| %>
      <tr>
        <td><%= t_facility_access_event_history.FIRST_NAME %></td>
        <td><%= t_facility_access_event_history.LAST_NAME %></td>
        <td><%= t_facility_access_event_history.PERSON_ID %></td>
        <td><%= link_to 'Show', t_facility_access_event_history %></td>
        <td><%= link_to 'Edit', edit_t_facility_access_event_history_path(t_facility_access_event_history) %></td>
        <td><%= link_to 'Destroy', t_facility_access_event_history, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New T facility access event history', new_t_facility_access_event_history_path %>

app/views/t_facility_access_event_histories/new.html.erb
<h1>New T Facility Access Event History</h1>

<%= render 'form' %>

<%= link_to 'Back', t_facility_access_event_histories_path %>

app/views/t_facility_access_event_histories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @t_facility_access_event_history.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @t_facility_access_event_history.last_name %>
</p>

<p>
  <strong>Person:</strong>
  <%= @t_facility_access_event_history.person_id %>
</p>

<%= link_to 'Edit', edit_t_facility_access_event_history_path(@t_facility_access_event_history) %> |
<%= link_to 'Back', t_facility_access_event_histories_path %>