config/routes.rb
Rails.application.routes.draw do
  resources :t_user_accounts
  resources :t_people
  resources :t_facility_access_event_histories
  resources :events

  resources :events do
    collection do
         get 'sold'
    end
  end
  resources :t_orders do
  end
  resources :t_order_items do
  end
  resources :t_facility_access_event_histories do
  end
  resources :t_persons do
  end

end

app/models/t_user_account.rb
class TUserAccount < ActiveRecord::Base
  self.table_name="T_USER_ACCOUNT"
end

app/controllers/t_user_accounts_controller.rb
class TUserAccountsController < ApplicationController
  before_action :set_t_user_account, only: [:show, :edit, :update, :destroy]

  # GET /t_user_accounts
  # GET /t_user_accounts.json
  def index
    @t_user_accounts = TUserAccount.all
  end

  # GET /t_user_accounts/1
  # GET /t_user_accounts/1.json
  def show
  end

  # GET /t_user_accounts/new
  def new
    @t_user_account = TUserAccount.new
  end

  # GET /t_user_accounts/1/edit
  def edit
  end

  # POST /t_user_accounts
  # POST /t_user_accounts.json
  def create
    @t_user_account = TUserAccount.new(t_user_account_params)

    respond_to do |format|
      if @t_user_account.save
        format.html { redirect_to @t_user_account, notice: 'T user account was successfully created.' }
        format.json { render :show, status: :created, location: @t_user_account }
      else
        format.html { render :new }
        format.json { render json: @t_user_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /t_user_accounts/1
  # PATCH/PUT /t_user_accounts/1.json
  def update
    respond_to do |format|
      if @t_user_account.update(t_user_account_params)
        format.html { redirect_to @t_user_account, notice: 'T user account was successfully updated.' }
        format.json { render :show, status: :ok, location: @t_user_account }
      else
        format.html { render :edit }
        format.json { render json: @t_user_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /t_user_accounts/1
  # DELETE /t_user_accounts/1.json
  def destroy
    @t_user_account.destroy
    respond_to do |format|
      format.html { redirect_to t_user_accounts_url, notice: 'T user account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_t_user_account
      @t_user_account = TUserAccount.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def t_user_account_params
      params[:t_user_account]
    end
end

app/helpers/t_user_accoun_ts_helper.rb
module TUserAccounTsHelper
end

app/views/t_user_accounts/_form.html.erb
<%= form_for(@t_user_account) do |f| %>
  <% if @t_user_account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@t_user_account.errors.count, "error") %> prohibited this t_user_account from being saved:</h2>

      <ul>
      <% @t_user_account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/t_user_accounts/edit.html.erb
<h1>Editing T User Account</h1>

<%= render 'form' %>

<%= link_to 'Show', @t_user_account %> |
<%= link_to 'Back', t_user_accounts_path %>

app/views/t_user_accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing T User Accounts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= @t_user_accounts.count %>
    <% @t_user_accounts.each do |t_user_account| %>
      <tr>
        <td><%= link_to 'Show', t_user_account %></td>
        <td><%= link_to 'Edit', edit_t_user_account_path(t_user_account) %></td>
        <td><%= link_to 'Destroy', t_user_account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New T user account', new_t_user_account_path %>

app/views/t_user_accounts/new.html.erb
<h1>New T User Account</h1>

<%= render 'form' %>

<%= link_to 'Back', t_user_accounts_path %>

app/views/t_user_accounts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_t_user_account_path(@t_user_account) %> |
<%= link_to 'Back', t_user_accounts_path %>