config/routes.rb
Rails.application.routes.draw do
  resources :t_user_accounts
  resources :t_people
  resources :t_facility_access_event_histories
  resources :events

  resources :events do
    collection do
         get 'sold'
    end
  end
  resources :t_orders do
  end
  resources :t_order_items do
  end
  resources :t_facility_access_event_histories do
  end
  resources :t_persons do
  end

end

app/models/t_person.rb
class TPerson < ActiveRecord::Base
   self.table_name="T_PERSON"
end

app/controllers/t_persons_controller.rb
class TPersonsController < ApplicationController
  before_action :set_t_person, only: [:show, :edit, :update, :destroy]

  # GET /t_people
  # GET /t_people.json
  def index
    @t_people = TPerson.all
  end

  # GET /t_people/1
  # GET /t_people/1.json
  def show
  end

  # GET /t_people/new
  def new
    @t_person = TPerson.new
  end

  # GET /t_people/1/edit
  def edit
  end

  # POST /t_people
  # POST /t_people.json
  def create
    @t_person = TPerson.new(t_person_params)

    respond_to do |format|
      if @t_person.save
        format.html { redirect_to @t_person, notice: 'T person was successfully created.' }
        format.json { render :show, status: :created, location: @t_person }
      else
        format.html { render :new }
        format.json { render json: @t_person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /t_people/1
  # PATCH/PUT /t_people/1.json
  def update
    respond_to do |format|
      if @t_person.update(t_person_params)
        format.html { redirect_to @t_person, notice: 'T person was successfully updated.' }
        format.json { render :show, status: :ok, location: @t_person }
      else
        format.html { render :edit }
        format.json { render json: @t_person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /t_people/1
  # DELETE /t_people/1.json
  def destroy
    @t_person.destroy
    respond_to do |format|
      format.html { redirect_to t_people_url, notice: 'T person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_t_person
      @t_person = TPerson.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def t_person_params
      params.require(:t_person).permit(:FIRST_NAME, :LAST_NAME)
    end
end

app/views/t_persons/_form.html.erb
<%= form_for(@t_person) do |f| %>
  <% if @t_person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@t_person.errors.count, "error") %> prohibited this t_person from being saved:</h2>

      <ul>
      <% @t_person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :FIRST_NAME %><br>
    <%= f.text_field :FIRST_NAME %>
  </div>
  <div class="field">
    <%= f.label :LAST_NAME %><br>
    <%= f.text_field :LAST_NAME %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/t_persons/edit.html.erb
<h1>Editing T Person</h1>

<%= render 'form' %>

<%= link_to 'Show', @t_person %> |
<%= link_to 'Back', t_person_path %>

app/views/t_persons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing T People</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @t_people.each do |t_person| %>
      <tr>
        <td><%= t_person.FIRST_NAME %></td>
        <td><%= t_person.LAST_NAME %></td>
        <td><%= link_to 'Show', t_person %></td>
        <td><%= link_to 'Edit', edit_t_person_path(t_person) %></td>
        <td><%= link_to 'Destroy', t_person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New T person', new_t_person_path %>

app/views/t_persons/new.html.erb
<h1>New T Person</h1>

<%= render 'form' %>

<%= link_to 'Back', t_people_path %>

app/views/t_persons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @t_person.FIRST_NAME %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @t_person.LAST_NAME %>
</p>

<%= link_to 'Edit', edit_t_person_path(@t_person) %> |
<%= link_to 'Back', t_people_path %>